import Head from 'next/head'

function Header() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <h1> Header</h1>
            </Head>

        </>
    )
}

export default Header